#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

date_default_timezone_set('Europe/Brussels');

use App\Kernel;
use App\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Dotenv\Dotenv;

(new Dotenv(false))->loadEnv(__DIR__.'/.env');

$_SERVER += $_ENV;
$_SERVER['SHELL_VERBOSITY'] = OutputInterface::VERBOSITY_NORMAL;

$kernel = new Kernel('dev', $_SERVER['DEBUG'] ?? false);

$application = new Application($kernel);
$application->run(new ArgvInput());

