services:
  _defaults:
    autowire: true
    bind:
      $emsUrl:  '%env(string:EMS_URL)%'
      $emsToken:  '%env(string:EMS_TOKEN)%'

  _instanceof:
    Symfony\Component\EventDispatcher\EventSubscriberInterface:
      tags: ['kernel.event_subscriber']

  App\:
    resource: '../src'

  App\Command\UploadFilesCommand:
    tags:
      - { name: console.command, command: api:upload:files }